; Generated by scriptc (LLVM backend) from /Users/mateuslage/Work/janela-wt-libmode/spike/ice3/t.ts. Do not edit.

%ScrStr = type { i64, i64, i64 }
%ScrLogArg = type { i32, i64 }
%ScrVt = type { i64, i64, ptr }
%ScrUnion = type { i64, i32, ptr, ptr, ptr, i64 }
%ScrClosure = type { i64, ptr, i64, ptr }
%ScrFfiTable = type { ptr, i64, i64, ptr, i8, ptr, ptr, i64, i64, i64, ptr, ptr }
%ScrRegex = type { i64, ptr, ptr, ptr }
%ScrArr = type { i64, i64, i64, i32, ptr, ptr, ptr, ptr }
%ScrError = type { i64, ptr, ptr, ptr, ptr }
%ScrClassObj = type { i64, i64, i64, ptr, ptr }
%ScrEmitter = type { i64, ptr, ptr, ptr }
%ScrStream = type { i64, ptr, ptr, ptr, ptr }
%ScrCaught = type { i64, i32, double, i8, ptr, ptr, ptr, ptr }
%ScrBytes = type { i64, i64, i32, ptr, ptr }
%ScrBox = type { i64, i32, ptr, ptr, ptr, i64 }
%ScrJsonBuf = type { ptr, i64, i64, ptr, i64, i64 }
%ScrDynPath = type { ptr, ptr, i64 }
%ScrIslandModule = type { ptr, ptr, i64, i64, i32, ptr, i64, i64 }
%ScrIslandEdge = type { ptr, ptr, ptr, i32 }

@scr_error_vts = external global [5 x %ScrVt]
declare void @scr_init()
declare void @scr_lib_init(i32, ptr)
declare void @scr_union_release(ptr)
declare ptr @scr_union_retain_v(ptr)
declare void @scr_union_release_v(ptr)
declare void @scr_jb_puts(ptr, ptr)
declare void @scr_jb_put_json_str(ptr, ptr)
declare void @scr_jb_init(ptr)
declare ptr @scr_jb_finish(ptr)
declare void @scr_console_log(i64, ptr)
declare void @scr_str_release(ptr)
declare zeroext i1 @scr_exc_pending()
declare void @scr_trap(ptr)

@sc_unit_0 = internal global %ScrUnion { i64 -1, i32 0, ptr null, ptr null, ptr null, i64 0 } ; u0 unit arm

@sc_cs_0 = internal constant [5 x i8] c"null\00"

@sc_g_e_y = internal global ptr null ; y
@sc_g_e__x25_loaded = internal global i1 false ; %loaded

@sc_bad_tag_msg = internal constant [44 x i8] c"scriptc: internal error: invalid union tag\0A\00"
define internal void @sc_bad_tag() #0 {
entry:
  call void @scr_trap(ptr @sc_bad_tag_msg)
  unreachable
}

define internal void @sc_jw_1(ptr %b, ptr %v) #0 { ; stringify string
entry:
  call void @scr_jb_put_json_str(ptr %b, ptr %v)
  ret void
}

define internal void @sc_jw_0(ptr %b, ptr %v) #0 { ; stringify union:u0
entry:
  %t0 = getelementptr inbounds %ScrUnion, ptr %v, i64 0, i32 1
  %t1 = load i32, ptr %t0
  switch i32 %t1, label %jwu.bad0 [ i32 0, label %jwu.a2 i32 1, label %jwu.a3 ]
jwu.a2:
  call void @scr_jb_puts(ptr %b, ptr @sc_cs_0) ; "null"
  br label %jwu.d1
jwu.a3:
  %t2 = getelementptr inbounds %ScrUnion, ptr %v, i64 0, i32 5
  %t3 = load ptr, ptr %t2
  call void @sc_jw_1(ptr %b, ptr %t3) ; string
  br label %jwu.d1
jwu.bad0:
  call void @sc_bad_tag()
  unreachable
jwu.d1:
  ret void
}

define internal void @sc_f__x25_init_0() #0 { ; %init.0
entry:
  %s4 = alloca %ScrJsonBuf
  %logargs = alloca [1 x %ScrLogArg]
  %t0 = load i1, ptr @sc_g_e__x25_loaded
  br i1 %t0, label %if.t0, label %if.j1
if.t0:
  ret void
if.j1:
  store i1 true, ptr @sc_g_e__x25_loaded
  %t1 = load ptr, ptr @sc_g_e_y
  call void @scr_union_release(ptr %t1)
  store ptr @sc_unit_0, ptr @sc_g_e_y
  %t2 = load ptr, ptr @sc_g_e_y
  %t3 = call ptr @scr_union_retain_v(ptr %t2)
  call void @scr_jb_init(ptr %s4)
  call void @sc_jw_0(ptr %s4, ptr %t3)
  %t5 = call ptr @scr_jb_finish(ptr %s4)
  %t6 = getelementptr inbounds %ScrLogArg, ptr %logargs, i64 0, i32 0
  store i32 1, ptr %t6
  %t7 = getelementptr inbounds %ScrLogArg, ptr %logargs, i64 0, i32 1
  store ptr %t5, ptr %t7
  call void @scr_console_log(i64 1, ptr %logargs)
  call void @scr_union_release(ptr %t3)
  call void @scr_str_release(ptr %t5)
  ret void
}

define internal void @sc_f__x25_main() #0 { ; %main
entry:
  call void @sc_f__x25_init_0()
  %t0 = call zeroext i1 @scr_exc_pending()
  br i1 %t0, label %exc.u0, label %exc.k1
exc.u0:
  ret void
exc.k1:
  ret void
}

declare void @scr_exc_print_uncaught()

define i32 @main(i32 %argc, ptr %argv) #0 {
entry:
  call void @scr_init()
  store i64 0, ptr getelementptr inbounds ([5 x %ScrVt], ptr @scr_error_vts, i64 0, i64 0, i32 0)
  store i64 4, ptr getelementptr inbounds ([5 x %ScrVt], ptr @scr_error_vts, i64 0, i64 0, i32 1) ; Error
  store i64 1, ptr getelementptr inbounds ([5 x %ScrVt], ptr @scr_error_vts, i64 0, i64 1, i32 0)
  store i64 1, ptr getelementptr inbounds ([5 x %ScrVt], ptr @scr_error_vts, i64 0, i64 1, i32 1) ; TypeError
  store i64 2, ptr getelementptr inbounds ([5 x %ScrVt], ptr @scr_error_vts, i64 0, i64 2, i32 0)
  store i64 2, ptr getelementptr inbounds ([5 x %ScrVt], ptr @scr_error_vts, i64 0, i64 2, i32 1) ; RangeError
  store i64 3, ptr getelementptr inbounds ([5 x %ScrVt], ptr @scr_error_vts, i64 0, i64 3, i32 0)
  store i64 3, ptr getelementptr inbounds ([5 x %ScrVt], ptr @scr_error_vts, i64 0, i64 3, i32 1) ; SyntaxError
  store i64 4, ptr getelementptr inbounds ([5 x %ScrVt], ptr @scr_error_vts, i64 0, i64 4, i32 0)
  store i64 4, ptr getelementptr inbounds ([5 x %ScrVt], ptr @scr_error_vts, i64 0, i64 4, i32 1) ; DOMException
  call void @scr_lib_init(i32 %argc, ptr %argv)
  call void @sc_f__x25_main()
  %exc = call zeroext i1 @scr_exc_pending()
  br i1 %exc, label %uncaught, label %ok
uncaught:
  call void @scr_exc_print_uncaught()
  %gu0 = load ptr, ptr @sc_g_e_y
  call void @scr_union_release(ptr %gu0) ; y
  ret i32 1
ok:
  %g0 = load ptr, ptr @sc_g_e_y
  call void @scr_union_release(ptr %g0) ; y
  ret i32 0
}

attributes #0 = { sanitize_address }
